apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark-team-a

resources:
  - namespace.yaml
  - spark-rbac.yaml

helmCharts:
  - name: spark-operator
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: spark-operator
    version: 1.1.27
    repo: https://googlecloudplatform.github.io/spark-on-k8s-operator

# Add this annotation to enable Helm
annotations:
  config.kubernetes.io/function: |
    exec:
      path: helm
      args:
        - template
        - --include-crds
        - --namespace
        - spark-team-a
