spark-operator:
  enableWebhook: true
  webhook:
    enable: true
    port: 8080
    namespaceSelector:
      matchLabels:
        spark-webhook: enabled

  serviceAccounts:
    spark:
      create: false
      name: spark-team-a
    webhook:
      create: true
      name: spark-operator-webhook

  rbac:
    create: true

  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

  metrics:
    enable: true
    endpoint: /metrics
    port: 10254

  batchScheduler:
    enable: true

  securityContext:
    runAsUser: 185
    fsGroup: 185

  webhookSecurityContext:
    runAsUser: 185
    fsGroup: 185

  logLevel: 2
