spark-operator:
  enableWebhook: true
  webhook:
    enable: true
    port: 8080
    namespaceSelector: "spark-webhook=enabled"  
    cleanupOnDelete: false  # Add this to prevent the cleanup job issues

  serviceAccounts:
    spark:
      create: false
      name: spark-team-a
    webhook:
      create: true
      name: spark-operator-webhook

  rbac:
    create: true

  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

  metrics:
    enable: true
    endpoint: /metrics
    port: 10254

  batchScheduler:
    enable: true

  securityContext:
    runAsNonRoot: true
    runAsUser: 185

  webhookConfig:
    mutatingWebhookConfigurationName: "spark-operator-webhook"
    cleanupEnabled: false  # Add this to prevent cleanup issues

  logLevel: 2

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 185
    fsGroup: 185