spark-operator:
  image:
    repository: ghcr.io/googlecloudplatform/spark-operator
    tag: v1beta2-1.3.8-3.1.1

  serviceAccounts:
    spark:
      create: false
      name: spark-team-a

  webhook:
    enable: true
    port: 8080

  metrics:
    enable: true
    endpoint: /metrics
    port: 10254

  batchScheduler:
    enable: true

  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534