# efs-test.yaml
---
# StorageClass for EFS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
# PersistentVolumeClaim using EFS StorageClass
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-test-pvc
  namespace: stock-analysis
spec:
  accessModes:
    - ReadWriteMany  # EFS supports ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
---
# Test Pod that mounts the PVC
apiVersion: v1
kind: Pod
metadata:
  name: efs-test-pod
  namespace: stock-analysis
spec:
  containers:
    - name: efs-test
      image: busybox
      command: ["sh", "-c", "while true; do echo $(date) >> /data/test.txt; sleep 5; done"]
      volumeMounts:
        - name: efs-volume
          mountPath: /data
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-test-pvc
