apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-02f73ca00af43d649
  directoryPerms: "755"
  gidRangeStart: "50000"
  gidRangeEnd: "70000000"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-demo
spec:
  containers:
  - name: efs-demo
    image: busybox
    command: ["sh", "-c"]
    args:
    - while true; do
        echo $(date -u) >> /mnt/efs/date.txt;
        sleep 5;
      done
    volumeMounts:
    - name: efs-pvc
      mountPath: "/mnt/efs"
  volumes:
  - name: efs-pvc
    persistentVolumeClaim:
      claimName: efs-claim
