apiVersion: v1
kind: Service
metadata:
  name: stock-analysis-ingress-nginx
  namespace: stock-analysis
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-analysis-ingress-nginx
  namespace: stock-analysis
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/upstream-vhost: "$host"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "false"
    kubernetes.io/ingress.class: "nginx"
    # Add caching for static content
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=static_cache:10m max_size=10g inactive=60m use_temp_path=off;
      proxy_cache static_cache;
      proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
      proxy_cache_valid 200 60m;
    # Add rate limiting
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: stock-analysis-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stock-analysis-frontend
            port:
              number: 80
