# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-analysis-frontend
  namespace: stock-analysis
  labels:
    app: stock-analysis-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-analysis-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: stock-analysis-frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/v2f5y6u4/stock-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stock-analysis-frontend
  namespace: stock-analysis
  labels:
    app: stock-analysis-frontend
spec:
  selector:
    app: stock-analysis-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
# ingress-nginx.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-analysis-ingress-nginx
  namespace: stock-analysis
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - http:
      paths:
      # Backend API route (must come before frontend for proper path matching)
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stock-analysis-backend
            port:
              number: 5000
      # Frontend route
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stock-analysis-frontend
            port:
              number: 80
