---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: karpenter-spoke-dev-20250312141856806600000005
  subnetSelectorTerms:
    - id: subnet-0064d2e92676b513f # Replace with your private subnet IDs
    # Add more subnet IDs as needed
  securityGroupSelectorTerms:
    - id: sg-0eb7354b166472cc9  # Replace with your node security group ID
  tags:
    karpenter.sh/discovery: "spoke-dev"
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 days